export enum PARKING_VOIRIE_TYPE {
  AERIEN = 'AERIEN',
  SOUTERRAIN = 'SOUTERRAIN',
  MIXTE = 'MIXTE'
}

export enum PARKING_VOIRIE_TYPE_STRUCTURE {
  OUVERT = 'OUVERT',
  FERME = 'FERME',
  COUVERT = 'COUVERT'
}
