export enum PARKING_VOIRIE_TYPE {
  PARKING = 'PARKING',
  VOIRIE = 'VOIRIE',
  NA = 'NA'
}

export enum PARKING_VOIRIE_TYPE_STRUCTURE {
  SOUTERRAIN = 'SOUTERRAIN',
  AERIEN = 'AERIEN',
  MIXTE = 'MIXTE'
}
